### ISSUE TITLE
Is a Stasis Dialplan actually required for Outbound call using ARI?

### ISSUE THREAD

**Issue by SueSingh** [skrusty/AsterNET.ARI#37]
Hi,

I am new to Asterisk and have written a sample in Asternet.ARI app. The app facilitates the dialing of 2 outbound calls and allows DTMF to play/stop MOH.

All the docs I have found indicate that I HAVE to have a simple Stasis dialplan, in order to do the above. E.g.
```
exten => 1001,1,NoOp()
same => n,Answer()
same => n,Stasis(StasisTest)
same => n,hangup()
```

However, I am able to enter Stasis WITHOUT the above dialplan existing. I've pasted the pertinent portion of the code I'm using below. 

```
static void Main()
{
    AriClient ActionClient = new AriClient(new StasisEndpoint("<IP>, 8088, "<username>", "<password>"), StasisTest);

    ActionClient.OnStasisStartEvent += c_OnStasisStartEvent;
    ActionClient.OnStasisEndEvent += c_OnStasisEndEvent;
    ActionClient.OnChannelDtmfReceivedEvent += ActionClientOnChannelDtmfReceivedEvent;

    ActionClient.Connect();
    Bridge SimpleBridge = ActionClient.Bridges.Create("mixing", Guid.NewGuid().ToString(), AppName); 

    ActionClient.Applications.Subscribe(AppName, "bridge:" + SimpleBridge.Id);
    Channel ch1 = ActionClient.Channels.Originate(strEndPoint1, null, null, null, null, "StasisTest");
    Channel ch2 = ActionClient.Channels.Originate(strEndPoint2, null, null, null, null, "StasisTest");
}
 static void c_OnStasisStartEvent(object sender, AsterNET.ARI.Models.StasisStartEvent e)
{
            // Answer channel
            ActionClient.Channels.Answer(e.Channel.Id);
        
            // Add channel to bridge
            ActionClient.Bridges.AddChannel(SimpleBridge.Id, e.Channel.Id, "participant");
}
```

I am trying to understand why one would require the Dialplan when I'm able to enter into Stasis without using a Dialplan. As I've explained, I'm a novice Asterisk user, so it's possible I'm overlooking some fundamental point.

Any info will be much appreciated.
Thank you

**Comment by claudiuolteanu** [comment]
Hi SueSingh,

If you don't redirect the channels to the dialplan, it is not required for outgoing calls. 

When you originate a channel from a Stasis application, you can also redirect it to the dialplan after the endpoint answers (using the context and extension parameters) [1]. This option can be used if you want to let the dialplan to handle the new channel. As you may already know, the dialplan is a scripting language that can be used to route or manipulate calls. So if you need to call a different application from the dialplan (like MixMonitor, MeetMe, etc.), because you don't want to implement your own version from Stasis, then you redirect the channel to a context and to an extension from dialpan. In the dialplan, you instruct Asterisk how to behave on that new channel.

There are situations in which you receive an incoming call, and you want to control it using your Stasis application. To do that, you need to redirect the channel to your Stasis application using the dialplan.
So if your dialplan contains the following code, then each channel generated by a call to extension 1001 (from-internal context) is redirected to a Stasis application named *StasisTest* .
```
[from-internal]
exten => 1001,1,NoOp()
same => n,Answer()
same => n,Stasis(StasisTest)
same => n,hangup()
```

In your example, the StasisStart event is raised because you subscribe your application (StasisTest)  to the originated channel for further events and updates by passing the 6th parameter. That parameter is not mandatory if you want to redirect your channel to the dialplan.

```csharp
Channel ch1 = ActionClient.Channels.Originate(strEndPoint1, null, null, null, null, "StasisTest");
```

If you have further questions, please let me know.

Cheers,
Claudiu

[1] - https://wiki.asterisk.org/wiki/display/AST/Asterisk+12+Channels+REST+API#Asterisk12ChannelsRESTAPI-originateWithId

**Comment by SueSingh** [comment]
Hi Claudiu,
Thank you kindly for taking the time to respond.

So, just to recap, I  need to specify context and extension parameters IFF I require the DialPlan to instruct the channel on how to behave. If I choose to instruct the channel via my code (in the my Stasis app), then I can skip creating a Dialplan?

Thank you.
Sue

**Comment by claudiuolteanu** [comment]
Yes, if you want to control your originated channels from a Stasis application, then you can skip the dialplan  section.

Your welcome,
Claudiu

**Comment by SueSingh** [comment]
Hi,
I _think_ the problem is this:
Originate(....)_ returns a Channel object (var x, in your case)
So you should be calling x.Ring(...)

**Comment by CShelton11** [comment]
Hi, x doesn't have a ring method.  Can you include a sample of how to make an outgoing phone call (using asternet.ari) without setting up a dial plan on the asterisk server?
